import { useState } from 'react';

// Gallery data with 8 sample logos
const galleryData = [
  {
    id: 1,
    title: 'TechFlow Solutions',
    category: 'Tech',
    imageUrl: 'https://picsum.photos/seed/tech1/400/400',
    description: 'Modern tech startup logo'
  },
  {
    id: 2,
    title: 'Fresh Bites Cafe',
    category: 'Food',
    imageUrl: 'https://picsum.photos/seed/food1/400/400',
    description: 'Organic restaurant branding'
  },
  {
    id: 3,
    title: 'Style Forward',
    category: 'Fashion',
    imageUrl: 'https://picsum.photos/seed/fashion1/400/400',
    description: 'Fashion boutique logo'
  },
  {
    id: 4,
    title: 'MediCare Plus',
    category: 'Health',
    imageUrl: 'https://picsum.photos/seed/health1/400/400',
    description: 'Healthcare service logo'
  },
  {
    id: 5,
    title: 'CloudSync Pro',
    category: 'Tech',
    imageUrl: 'https://picsum.photos/seed/tech2/400/400',
    description: 'Cloud computing platform'
  },
  {
    id: 6,
    title: 'Green Harvest',
    category: 'Food',
    imageUrl: 'https://picsum.photos/seed/food2/400/400',
    description: 'Sustainable farming brand'
  },
  {
    id: 7,
    title: 'Elegance Wear',
    category: 'Fashion',
    imageUrl: 'https://picsum.photos/seed/fashion2/400/400',
    description: 'Luxury fashion brand'
  },
  {
    id: 8,
    title: 'Wellness Hub',
    category: 'Health',
    imageUrl: 'https://picsum.photos/seed/health2/400/400',
    description: 'Wellness center logo'
  }
];

const categories = ['All', 'Tech', 'Food', 'Fashion', 'Health'];

const ExamplesGallery = () => {
  const [activeFilter, setActiveFilter] = useState('All');
  const [filteredData, setFilteredData] = useState(galleryData);

  const handleFilterChange = (category) => {
    setActiveFilter(category);
    
    if (category === 'All') {
      setFilteredData(galleryData);
    } else {
      setFilteredData(galleryData.filter(item => item.category === category));
    }
  };

  return (
    <section id="examples" className="py-20 bg-gradient-to-br from-purple-50 to-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Logo Examples Gallery
          </h2>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            See professional logos generated by our AI in seconds
          </p>
        </div>

        {/* Filter Tabs */}
        <div className="flex flex-wrap justify-center gap-2 mb-12">
          {categories.map((category) => (
            <button
              key={category}
              onClick={() => handleFilterChange(category)}
              className={`px-6 py-2 rounded-full font-medium transition-all duration-200 ${
                activeFilter === category
                  ? 'bg-purple-600 text-white shadow-lg transform scale-105'
                  : 'bg-white text-gray-700 hover:bg-purple-100 border border-purple-200'
              }`}
            >
              {category}
            </button>
          ))}
        </div>

        {/* Gallery Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {filteredData.map((item, index) => (
            <div
              key={item.id}
              className="group relative bg-white rounded-xl shadow-lg hover:shadow-xl transition-all duration-300 transform hover:scale-105 overflow-hidden animate-fade-in"
            >
              {/* Logo Image */}
              <div className="aspect-square relative overflow-hidden bg-gradient-to-br from-purple-50 to-blue-50 p-8">
                <img
                  src={item.imageUrl}
                  alt={item.title}
                  className="w-full h-full object-contain transition-transform duration-300 group-hover:scale-110"
                />
                
                {/* Hover Overlay - Hidden by default */}
                <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end">
                  <div className="p-4 text-white">
                    <p className="text-sm font-medium">Generated in 8 seconds</p>
                  </div>
                </div>
              </div>

              {/* Card Content */}
              <div className="p-6">
                <div className="flex items-center justify-between mb-2">
                  <span className="inline-block px-3 py-1 bg-purple-100 text-purple-700 text-xs font-medium rounded-full">
                    {item.category}
                  </span>
                  <div className="flex items-center text-gray-400">
                    <svg className="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M10 12a2 2 0 100-4 2 2 0 000 4z"/>
                      <path fillRule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clipRule="evenodd"/>
                    </svg>
                    <span className="text-xs">1.2k</span>
                  </div>
                </div>
                <h3 className="font-semibold text-gray-900 text-sm mb-1">{item.title}</h3>
                <p className="text-gray-600 text-xs">{item.description}</p>
              </div>
            </div>
          ))}
        </div>

        {/* Call to Action */}
        <div className="text-center mt-16">
          <div className="bg-gradient-to-r from-purple-600 to-blue-600 rounded-2xl p-8 text-white">
            <h3 className="text-2xl font-bold mb-4">
              Ready to Create Your Logo?
            </h3>
            <p className="text-purple-100 mb-6 max-w-2xl mx-auto">
              Join thousands of businesses who have created professional logos with our AI-powered platform
            </p>
            <button
              onClick={() => window.location.href = '/generate'}
              className="bg-white text-purple-600 font-bold py-3 px-8 rounded-lg hover:bg-gray-100 transition-colors duration-200 transform hover:scale-105 shadow-lg"
            >
              Start Creating Now
            </button>
          </div>
        </div>
      </div>
    </section>
  );
};

export default ExamplesGallery;
